- ID: 430
- Name: WEST
- Description: Phenotyping leaf epidermis by optical tomography and computer vision
    to evaluate stomatal patterning across natural diversity and transgenic lines
    of Sorghum and Setaria
- PIName: Dr. Andrew Leakey
- Organization: University of Illinois Urbana-Champaign
- Department: Plant Biology
- FieldOfScience: Plant Biology
- Sponsor: 
  - CampusGrid: 
    - ID: 14
    - Name: OSG Connect