LongName: Louisiana State University LSU_SuperMIC
Description: The Louisiana State University LSU_SuperMIC cluster 

ID: 10245

AddressLine1: Baton Rouge, Louisiana 70803
City: Baton

Country: US
State: Louisiana
Zipcode: "70808"

Latitude: 30.471165
Longitude: -91.147385
