LongName: Pittsburgh Supercomputing Center
Description: The Pittsburgh Supercomputing Center PSC-Bridges cluster 

ID:
AddressLine1: 300 S Craig St
City: Pittsburgh

Country: United States
State: Pennsylvania
Zipcode: "15213"

Latitude: 40.444035
Longitude: -79.959987
