LongName: University of Maryland UMD_SIAB
Description: The University of Maryland UMD_SIAB cluster 

ID:

AddressLine1: College Park
City: College

Country: US
State: Maryland
Zipcode: "20742"

Latitude: 38.989697
Longitude: -76.937759
