Disable: false
GroupDescription: Resource group for production VM hosts
GroupID: 441
Production: true
Resources:
  VM01:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm01.grid.iu.edu
    ID: 801
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
  VM02:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm02.grid.iu.edu
    ID: 802
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
  VM03:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm03.grid.iu.edu
    ID: 803
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
  VM04:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm04.grid.iu.edu
    ID: 804
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
  VM05:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm05.grid.iu.edu
    ID: 805
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
  VM06:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm06.grid.iu.edu
    ID: 806
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
  VM07:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm07.grid.iu.edu
    ID: 807
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
  VM08:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm08.grid.iu.edu
    ID: 808
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
  VM09:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm09.grid.iu.edu
    ID: 809
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
  VM10:
    ContactLists:
      Administrative Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Security Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
      Submitter Contact:
        Primary:
          ID: 238d6d2794a7aa5391ae3d13297561a015026bb2
          Name: Scott Teige
    Description: A VM host
    Disable: false
    FQDN: vm10.grid.iu.edu
    ID: 810
    Services:
      Virtual Machine Host:
        Description: Physical machine hosting VMs
    VOOwnership:
      Ops: 100
SupportCenter: OSG-GOC
