LongName: Berkeley Lab Research Computing Cluster
Description: Institutional computing center for LBNL
ID: 
AddressLine1: One Cyclotron Road
City: Berkeley
Country: USA
Zipcode: "94720"
Latitude: 37.866825
Longitude: -122.3
