LongName: The College of New Jersey
Description: The The College of New Jersey NEWJERSEY_ELSA cluster 

ID: 

AddressLine1: 2000 Pennington Rd, Ewing Township
City: Ewing

Country: US
State: New Jersey
Zipcode: 08618

Latitude: 40.259987
Longitude: -74.790909
