AddressLine1: 118 Schorr Center
Country: United States
Description: The Holland Computing Center at the University of Nebraska-Lincoln
ID: 10065
Latitude: 40.819818
Longitude: -96.705651
State: NE
Zipcode: '68588'
